import { isElement } from 'react-addons-test-utils';
import { mapValues } from 'lodash';

/*
 * Returns an immutable Map containing values generated by the randomValue
 * function of each control.
 */
const randomValues = (properties) => {
  return mapValues(properties, (ElementOrObject) => {
    if (isElement(ElementOrObject)) {
      if (typeof ElementOrObject.props.value !== 'undefined') {
        return ElementOrObject.props.value;
      }

      return ElementOrObject.type.randomValue(ElementOrObject.props);
    }

    return randomValues(ElementOrObject);
  });
};

export default randomValues;
