import {isElement} from 'react-addons-test-utils';

/*
 * Returns an immutable Map containing values generated by the randomValue
 * function of each control.
 */
const randomValues = (properties) => {
  return properties.map((immutableObject) => {
    const ElementOrObject = immutableObject.toJS();
    if (isElement(ElementOrObject)) {
      if (typeof ElementOrObject.props.value !== 'undefined') {
        return ElementOrObject.props.value;
      }

      return ElementOrObject.type.randomValue(ElementOrObject.props);
    }

    return randomValues(immutableObject);
  });
};

export default randomValues;
